package co.in.nnj.learn.jee.eduinst.boundry;

public class UsageFoundException extends RuntimeException {
    public UsageFoundException(String message) {
        super(message);
    }
}

